---
title: "Taller Bitcoin"
author: "Francisco Flor"
date: "25/8/2022"
output: html_document
---

```{r setup, include=FALSE}


library(rmarkdown)
library(foreign) 

library(openxlsx)

library(tidyverse)

library(tseries)

library(astsa)

library(forecast)

library(timsac)

library(vars)

library(dynlm)

library(nlme)

library(urca)

library(quantmod)

library(lubridate)



datat <- read.xlsx("D:\\ECONOMETRIA 2\\DBT.xlsx")


```


```{r , echo=TRUE,warning=FALSE,message=FALSE}
attach(datat)


#especificar periodo de tiempo
#covierte la  base a serie de tiempo
arima.ts=ts(datat$BTC, start=c(2015,1), frequency = 12)

#Se especifica la frecuencia y el periodo de inicio. 

start(arima.ts); end(arima.ts)

arima.ts

#convierte en log para reducir temas de dispersión

larima.ts=log(arima.ts)

plot(larima.ts, ylab="log BTC")

#RAIZ UNITARIA Dickey Fuller Aumentado

larima.tsur= ur.df(larima.ts, type="none", selectlags = "AIC")


summary(larima.tsur)

#ninguna es estadisticamente significativa
  

```

```{r , echo=TRUE,warning=FALSE,message=FALSE}

#ESTA ES PARA PRIMERAS DIFERENCIAS APLICADO A LA VARIABLE QUE TENEMOS EN LOG
larimadif=diff(larima.ts)


#ESTO SIRVE PARA COMPROBAR
larimadifur= ur.df(larimadif, type="none", selectlags = "AIC")

summary(larimadifur)

#Aqui es estadisticamente significativo el z.lag.1


```

```{r , echo=TRUE,warning=FALSE,message=FALSE}

#O
ndiffs(larimadif)
#como aparece el valor de 0 quiere decir que no necesita diferenciar y que es estacionario

plot(larimadif)
plot(larima.ts)

#como se ve como el grafico vemos que ya se a hecho estacionaria


#Correlograma
#esto es para correr el modelo arma o arima

ggtsdisplay(larima.ts)

ggtsdisplay(larimadif)

```

```{r , echo=TRUE,warning=FALSE,message=FALSE}

#ARIMA

#uso la variable sin diferenciar

modeloarimah=arima(larima.ts,order = c(1,2,2))

summary(modeloarimah)

#RMSE SIGNIFICA LA RAÌZ MEDIA DEL ERROR ESTÁNDAR, ESTO DEBE SER MENOR QUE 5
#NINGUNO DEBERÍA SER MAYOR A 5
#SI EL INDICAR AIC ES EL MENOR, ESE SERÁ EL QUE MEJOR PREDICE

coeftest(modeloarimah)
#ESTO ES LA SIGNIFICANCIA
#EN ESTE CASO NO SE ANALIZAN LOS ESTIMADORES PORQUE LA SERIE ES MUY VOLÁTIL


```

```{r , echo=TRUE,warning=FALSE,message=FALSE}

autoplot(modeloarimah)


tsdiag(modeloarimah)
#como los puntos estan sobre las lineas segmentadas no se rechaza la ho. Y existe ruido blanco. 


Box.test(residuals(modeloarimah),type = "Ljung-Box")
#Ljung Box test para ruido blanco
#EL P VALUE ES MAYOR A 0.05 POR EN DE NO SE RECHAZA HO: RUIDO BLANCO; ES DECIR QUE EXISTE RUIDO BLANCO Y ES UN BUEN MODELO


```

```{r , echo=TRUE,warning=FALSE,message=FALSE}

#Auto Arima

arimah=auto.arima(larima.ts, stepwise = FALSE, approximation = FALSE, trace = TRUE)

summary(arimah)


coeftest(arimah)


autoplot(arimah)

#EL AUTOARIMA SACA LAS MEDIAS MOVILES ESTACIONALES SACADAS COMO EL SMA,
#EL LA GRÁFICA HAY 12 PUNTOS PORQUE EL PERIODO ES DE 12 MESES
#SI LOS PUNTOS ESTAN AFUERA DEL MARCO DE LA CIRCUNFERENCIA, SIGNIFICA QUE HAY PROBLEMA DE ESTABILIDAD ESTRUCTURAL
#LA ESTABILIDAD ESTRUCTURAL SE SOLUCIONA CORRIGIENDO DATOS ATIPICOS O AUMENTANDO LOS AUTOREGRESIVOS
#LOS PROBLEMAS DE ESTABILIDAD ESTRUCTURAL PUEDEN APARECER, ES CUANDO SACAMOS LA DIFERENCIA DE LAS VARIABLES, LA FUNCIOMN DE AUTOCORRELACIÓN SIMPLE NO SE CORRIGE
#Ljung Box test para ruido blanco

tsdiag(arimah)


Box.test(residuals(arimah),type = "Ljung-Box")

#EL P VALUE ES MAYOR A 0.05 POR ENDE NO SE RECHAZA HO: RUIDO BLANCO; ES DECIR QUE EXISTE RUIDO BLANCO Y ES UN BUEN MODELO



```

```{r , echo=TRUE,warning=FALSE,message=FALSE}

#Comparación de criterio de información

modeloarimah$aic

arimah$aic

#pronostico

pronosticoh <- forecast::forecast(modeloarimah, h=5)

#FORECAST ES UN COMANDO DE PROYECCIÓN
#H:5 SON LOS PERIDOS QUE VAMOS A PROYECTAR EN ESTE CASO COMO ES H=5 VAMOS A PROYECTAR 5 PERIODOS, EN ESTE CASO MESES

pronosticoh


plot(pronosticoh)


```


#Precio BITCOIN EN Julio 2022: 23,336.90	